before:
  hooks:
    - go mod tidy
    - ENV=production go generate ./...
builds:
  - id: hkx
    goos:
      - linux
archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
