before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
