### HORKRUXES CONFIGURATION ###

# URL of the server
url = "localhost" # for local use: "localhost" or "127.0.0.1"

# Custom name to display
name = "horkruxes" # default: "horkruxes"

# Is this server private ? 
# If private, only keys added in the /keys folder will be able to post
private = false # default: false
