// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "AGPLv3",
            "url": "https://www.gnu.org/licenses/agpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/all": {
            "get": {
                "description": "get string by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Show all messages (original messages and comments) without any more structure",
                "operationId": "all",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Message"
                            }
                        }
                    }
                }
            }
        },
        "/comments/{uuid}": {
            "get": {
                "description": "get string by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Show comments to a specific message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of original message corresponding to comments",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Message"
                            }
                        }
                    }
                }
            }
        },
        "/message": {
            "get": {
                "description": "get string by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Show all original messages (for the front page)",
                "operationId": "messages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Message"
                            }
                        }
                    }
                }
            }
        },
        "/message/{uuid}": {
            "get": {
                "description": "get string by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Show a specific message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Message UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Message"
                        }
                    }
                }
            }
        },
        "/new": {
            "post": {
                "description": "get string by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Post a new message"
            }
        },
        "/user/{pubkey}": {
            "get": {
                "description": "get string by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Show messages of a specific user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Author ed25519 public key",
                        "name": "pubkey",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Message"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Message": {
            "type": "object",
            "properties": {
                "authorBase64": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "displayedName": {
                    "description": "Stored and given by user",
                    "type": "string"
                },
                "id": {
                    "description": "Stored and generated",
                    "type": "string"
                },
                "messageID": {
                    "description": "Used if the message is a comment to a publication",
                    "type": "string"
                },
                "pod": {
                    "description": "Not saved in db but tell where it is sent from so remains in JSON",
                    "type": "string"
                },
                "signatureBase64": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "Horkruxes API",
	Description: "Swagger for the Horkruxes API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
