name: Release Go project

on:
  push:
    branches: [ master ]
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else
  pull_request:
    branches: [ master ]
    

jobs:
  build:
    name: Test, Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Release # Only for a new tag on master
        uses: goreleaser/goreleaser-action@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
